sudo: required
dist: trusty
language: node_js
node_js:
  - node
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
deploy:
  provider: npm
  email: "kvdb@d-centralize.nl"
  on:
    tags: true
env:
  global:
    secure: mr8HwX06PKPSZfrorqOfWbQdf0OuNp6SECFCXa1wu79luH5cGcpfRxYLXWipl93bo/o3NramjmtNYdPUe3EwSZnxhh8TAtTylFE/+BYD4PzvvtwWzeTZNmMu91SFwv0RwhIdDgSBZnuDc6FZEkDJMmB2PoUfEccDT3K6Lj3fsFubCwRbrnAw7kjiMQhBza0MvBJlbnCSzjvDLJjlsRsWeFIVh9c55RZBg+hCv+1VixEhAB8PWKX8W0XkPl9E/XJw2qDwBIT7ZtRX1b8g1N462pt8E8EzJLwKcJFZTWSFnKyQzHXGuKi6MkUPhtG2yLiYAY3VWfSgXblnIZhfortwC9PcYbSDCtji/vJXd3+rt1+ag0DOO8UX1ukuFywpGd3vdMc0dQ3JioOW67iIb1l/FhachvmtRiLK/9yZv4oVhgE8u4/gSD2pEj4Y7UDpS/5vmDc18kcWXmMfSCDRD7W49WGNC56tWJHMjV05PSxj7nhIGEwUvd1Arr3pj3VJ7d+Ef5cLyxDCCL1vlJx7H6MkSEUuOrOmW51ZRhDbT3F2C01SLAiRw3k1+kr1HponTg7A4epbF79iVvNaui29oxYry85qK8n5qWIAODUn51/o06kPSeBfSlpEg8Gcke4LkDz08dI2BZkYZNXBZc0TrmNAsGXVd+doQJqMkKk3ed8jqhM=
